Create codeql-analysis.yml
coreruleset/secrules_parsing pull request #28
Opened 2022-09-06 11:13 UTC by fzipi

Add codeQL scanning

2022-10-01 16:06 UTC, theseion requested changes

2022-10-01 16:06 UTC, theseion commented on .github/workflows/codeql-analysis.yml
> +# ******** NOTE ********
Remove the note.

2022-10-01 16:06 UTC, theseion commented on .github/workflows/codeql-analysis.yml
> +    - name: Autobuild
We can probably remove this step.

2022-10-02 12:25 UTC, fzipi commented on .github/workflows/codeql-analysis.yml
> +# ******** NOTE ********
Done.

2022-10-02 12:25 UTC, fzipi commented on .github/workflows/codeql-analysis.yml
> +    - name: Autobuild
Removed.

2022-10-02 13:02 UTC, theseion approved these changes

2022-10-02 13:10 UTC, merged